-- Online shopping trends data analysis

SELECT * FROM shopping.customers LIMIT 5;
SELECT * FROM shopping.orders LIMIT 5;
SELECT * FROM shopping.products LIMIT 5;
SELECT * FROM shopping.sales LIMIT 5;


-- Top 10 customers who spent made the most purchase to identify the most fequent buyers.
-- Could be useful for creating customer loyalty programs for frequent buyers or to detect potential bulk buyers.
SELECT c.customer_id,
	c.customer_name,
    COUNT(s.sales_id) AS num_of_purchase
FROM customers AS c
LEFT JOIN orders AS o
ON c.customer_id = o.customer_id
LEFT JOIN sales AS s
ON o.order_id = s.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY num_of_purchase DESC
LIMIT 10;


-- Top 10 customers who spent the most money to identify the most valuable customers.
SELECT c.customer_id,
	c.customer_name,
	SUM(total_price) AS total_spent
FROM customers AS c
LEFT JOIN orders AS o
ON c.customer_id = o.customer_id
LEFT JOIN sales AS s
ON o.order_id = s.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 10;


-- Overall average AOV across all customers
-- AOV: total revenue / num of distinct orders
WITH avg_aov_cte AS (
	SELECT ROUND(SUM(s.total_price) / COUNT(DISTINCT o.order_id), 2) AS avg_aov
	FROM sales AS s
	INNER JOIN orders AS o
	ON s.order_id = o.order_id
),
-- Analysis: Overall average AOV is 1039.07

/*
AOV Per Customer and Respective Customer Segment to categorize customers.
High-Value Customers: Spend above 1.5x the overall AOV.
Mid-Value Customers: Spend between 0.75x and 1.5x of the overall AOV.
Low-Value Customers: Spend below 0.75x of the overall AOV.
*/
	customer_segments AS(
    SELECT
	c.customer_id,
    c.customer_name,
    ROUND(SUM(s.total_price) / COUNT(DISTINCT o.order_id), 2) AS aov_per_customer,
    CASE
		WHEN ROUND(SUM(s.total_price) / COUNT(DISTINCT o.order_id), 2) > avg_aov_cte.avg_aov * 1.5 THEN 'High-Value Customer'
        WHEN ROUND(SUM(s.total_price) / COUNT(DISTINCT o.order_id), 2) BETWEEN avg_aov_cte.avg_aov * 0.75 AND avg_aov_cte.avg_aov * 1.5 THEN 'Middle-Value Customer'
        ELSE 'Low-Value Customer' END AS customer_segment
FROM customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
INNER JOIN sales AS s
ON o.order_id = s.order_id
INNER JOIN avg_aov_cte
GROUP BY c.customer_id, c.customer_name, avg_aov
ORDER BY aov_per_customer DESC
)

-- Number of customers per customer segment
SELECT 
	customer_segment,
    COUNT(*) AS count
FROM customer_segments
GROUP BY customer_segment;
-- Analysis: Most customers are Middle-Value Customers


-- Best-selling product categories understand which product type sells the most, could be helpful in inventory planning.
SELECT p.product_type,
	SUM(s.quantity) AS total_sold,
	SUM(s.total_price) AS product_revenue
FROM products AS p
LEFT JOIN sales AS s
ON p.product_id = s.product_id
GROUP BY p.product_type
ORDER BY total_sold;
/*
Analysis:
The product type with the highest revenue is the Shirt Category and with the lowest revenue is the Jacket Category.
The best selling product type is the Shirt Category and the least selling is the Trousers Category. 
*/


-- Identify seasonal trends by calculating monthly revenue could be helpful in analyzing shopping patterns throughout the year.
SELECT DATE_FORMAT(o.order_date, '%m') AS order_month, 
       SUM(s.total_price) AS monthly_revenue
FROM orders o
INNER JOIN sales s ON o.order_id = s.order_id
GROUP BY order_month
ORDER BY monthly_revenue;
-- Analysis: Highest selling month is the 10th (October) and the lowest selling is the 3rd (March) month.


-- Average delivery time for orders.
-- Could be useful for logistics and improving customer experience.
SELECT ROUND(AVG(DATEDIFF(delivery_date, order_date)), 2) AS avg_delivery_days
FROM orders;
-- Analysis: On average the products are delivered around 14 days.

-- Customers who made more than 1 order, could be helpful for segmenting customers based on loyalty.
SELECT c.customer_id,
	c.customer_name,
	COUNT(o.order_id) AS total_orders
FROM customers AS c
LEFT JOIN orders AS o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING total_orders > 1
ORDER BY total_orders DESC;
-- Analysis: Highest number of orders is 6, made by Kristofor Roos with a customer id of 571.


-- Most popular product color and size, could be helpful in optimizing the inventory by stocking the most demanded variations.
SELECT
	p.product_type,
    p.colour,
    p.size,
    SUM(s.quantity) AS num_of_sold,
    SUM(s.total_price) AS total_revenue
FROM products AS p
LEFT JOIN sales AS s
ON p.product_id = s.product_id
GROUP BY p.product_type, p.colour, p.size
ORDER BY num_of_sold DESC;
-- Analysis: Most popular product is a S sized blue Jacket.


-- The total revenue generated by each city, could be helpful in analyzing which cities contribute the most to sales.
SELECT
    c.city,
    SUM(s.total_price) AS total_revenue
FROM customers AS c
LEFT JOIN orders AS o
ON c.customer_id = o.customer_id
LEFT JOIN sales AS s
ON o.order_id = s.order_id
GROUP BY c.city
ORDER BY total_revenue DESC;
-- Analysis: The city with the higest revenue is Port Hannahburgh with a total revenue of 7632.


-- Gender-based purchasing behavior, could be helpful in analyze differences in spending across gender groups.
SELECT 
	c.gender,
    SUM(s.quantity) AS num_of_purchase,
    SUM(s.total_price) AS total_revenue
FROM customers AS c
LEFT JOIN orders AS o
ON c.customer_id = o.customer_id
LEFT JOIN sales AS s
ON o.order_id = s.order_id
GROUP BY c.gender
ORDER BY total_revenue DESC;
-- Analysis: Female customers have the highest purchase number and total revenue


-- Customers who abandoned their cart (placed an order but did not receive delivery), could be helpful in improving customer retention
SELECT 
	c.customer_id, 
	c.customer_name, 
    o.order_id, 
    o.order_date
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
LEFT JOIN sales s ON o.order_id = s.order_id
WHERE s.order_id IS NULL;
